/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ChangesChangeIdRouteImport } from './routes/changes/$changeId'
import { Route as DecisionsDecisionIdRouteImport } from './routes/decisions/$decisionId'
import { Route as ReposIndexRouteImport } from './routes/repos/index'
import { Route as ReposNewRouteImport } from './routes/repos/new'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ApiDevPushRouteImport } from './routes/api/dev/push'
import { Route as ApiGitCredentialsRouteImport } from './routes/api/git/credentials'
import { Route as ReposRepoSlugIndexRouteImport } from './routes/repos/$repoSlug/index'
import { Route as ReposRepoSlugDecisionsRouteImport } from './routes/repos/$repoSlug/decisions'
import { Route as ApiChangesChangeIdLiveRouteImport } from './routes/api/changes/$changeId/live'
import { Route as ApiReposRepoSlugIndexRouteImport } from './routes/api/repos/$repoSlug/index'
import { Route as ApiReposRepoSlugSessionsRouteImport } from './routes/api/repos/$repoSlug/sessions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesChangeIdRoute = ChangesChangeIdRouteImport.update({
  id: '/changes/$changeId',
  path: '/changes/$changeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsDecisionIdRoute = DecisionsDecisionIdRouteImport.update({
  id: '/decisions/$decisionId',
  path: '/decisions/$decisionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposNewRoute = ReposNewRouteImport.update({
  id: '/repos/new',
  path: '/repos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevPushRoute = ApiDevPushRouteImport.update({
  id: '/api/dev/push',
  path: '/api/dev/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitCredentialsRoute = ApiGitCredentialsRouteImport.update({
  id: '/api/git/credentials',
  path: '/api/git/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRepoSlugIndexRoute = ReposRepoSlugIndexRouteImport.update({
  id: '/repos/$repoSlug/',
  path: '/repos/$repoSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRepoSlugDecisionsRoute = ReposRepoSlugDecisionsRouteImport.update({
  id: '/repos/$repoSlug/decisions',
  path: '/repos/$repoSlug/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangesChangeIdLiveRoute = ApiChangesChangeIdLiveRouteImport.update({
  id: '/api/changes/$changeId/live',
  path: '/api/changes/$changeId/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReposRepoSlugIndexRoute = ApiReposRepoSlugIndexRouteImport.update({
  id: '/api/repos/$repoSlug/',
  path: '/api/repos/$repoSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReposRepoSlugSessionsRoute =
  ApiReposRepoSlugSessionsRouteImport.update({
    id: '/api/repos/$repoSlug/sessions',
    path: '/api/repos/$repoSlug/sessions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/changes/$changeId': typeof ChangesChangeIdRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/repos/new': typeof ReposNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/repos/': typeof ReposIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/dev/push': typeof ApiDevPushRoute
  '/api/git/credentials': typeof ApiGitCredentialsRoute
  '/repos/$repoSlug/decisions': typeof ReposRepoSlugDecisionsRoute
  '/repos/$repoSlug/': typeof ReposRepoSlugIndexRoute
  '/api/changes/$changeId/live': typeof ApiChangesChangeIdLiveRoute
  '/api/repos/$repoSlug/sessions': typeof ApiReposRepoSlugSessionsRoute
  '/api/repos/$repoSlug/': typeof ApiReposRepoSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/changes/$changeId': typeof ChangesChangeIdRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/repos/new': typeof ReposNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/repos': typeof ReposIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/dev/push': typeof ApiDevPushRoute
  '/api/git/credentials': typeof ApiGitCredentialsRoute
  '/repos/$repoSlug/decisions': typeof ReposRepoSlugDecisionsRoute
  '/repos/$repoSlug': typeof ReposRepoSlugIndexRoute
  '/api/changes/$changeId/live': typeof ApiChangesChangeIdLiveRoute
  '/api/repos/$repoSlug/sessions': typeof ApiReposRepoSlugSessionsRoute
  '/api/repos/$repoSlug': typeof ApiReposRepoSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/changes/$changeId': typeof ChangesChangeIdRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/repos/new': typeof ReposNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/repos/': typeof ReposIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/dev/push': typeof ApiDevPushRoute
  '/api/git/credentials': typeof ApiGitCredentialsRoute
  '/repos/$repoSlug/decisions': typeof ReposRepoSlugDecisionsRoute
  '/repos/$repoSlug/': typeof ReposRepoSlugIndexRoute
  '/api/changes/$changeId/live': typeof ApiChangesChangeIdLiveRoute
  '/api/repos/$repoSlug/sessions': typeof ApiReposRepoSlugSessionsRoute
  '/api/repos/$repoSlug/': typeof ApiReposRepoSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/me'
    | '/changes/$changeId'
    | '/decisions/$decisionId'
    | '/repos/new'
    | '/sessions/$sessionId'
    | '/repos/'
    | '/sessions/'
    | '/settings/'
    | '/api/dev/push'
    | '/api/git/credentials'
    | '/repos/$repoSlug/decisions'
    | '/repos/$repoSlug/'
    | '/api/changes/$changeId/live'
    | '/api/repos/$repoSlug/sessions'
    | '/api/repos/$repoSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/me'
    | '/changes/$changeId'
    | '/decisions/$decisionId'
    | '/repos/new'
    | '/sessions/$sessionId'
    | '/repos'
    | '/sessions'
    | '/settings'
    | '/api/dev/push'
    | '/api/git/credentials'
    | '/repos/$repoSlug/decisions'
    | '/repos/$repoSlug'
    | '/api/changes/$changeId/live'
    | '/api/repos/$repoSlug/sessions'
    | '/api/repos/$repoSlug'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/me'
    | '/changes/$changeId'
    | '/decisions/$decisionId'
    | '/repos/new'
    | '/sessions/$sessionId'
    | '/repos/'
    | '/sessions/'
    | '/settings/'
    | '/api/dev/push'
    | '/api/git/credentials'
    | '/repos/$repoSlug/decisions'
    | '/repos/$repoSlug/'
    | '/api/changes/$changeId/live'
    | '/api/repos/$repoSlug/sessions'
    | '/api/repos/$repoSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMeRoute: typeof ApiMeRoute
  ChangesChangeIdRoute: typeof ChangesChangeIdRoute
  DecisionsDecisionIdRoute: typeof DecisionsDecisionIdRoute
  ReposNewRoute: typeof ReposNewRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  ReposIndexRoute: typeof ReposIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiDevPushRoute: typeof ApiDevPushRoute
  ApiGitCredentialsRoute: typeof ApiGitCredentialsRoute
  ReposRepoSlugDecisionsRoute: typeof ReposRepoSlugDecisionsRoute
  ReposRepoSlugIndexRoute: typeof ReposRepoSlugIndexRoute
  ApiChangesChangeIdLiveRoute: typeof ApiChangesChangeIdLiveRoute
  ApiReposRepoSlugSessionsRoute: typeof ApiReposRepoSlugSessionsRoute
  ApiReposRepoSlugIndexRoute: typeof ApiReposRepoSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes/$changeId': {
      id: '/changes/$changeId'
      path: '/changes/$changeId'
      fullPath: '/changes/$changeId'
      preLoaderRoute: typeof ChangesChangeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/$decisionId': {
      id: '/decisions/$decisionId'
      path: '/decisions/$decisionId'
      fullPath: '/decisions/$decisionId'
      preLoaderRoute: typeof DecisionsDecisionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/new': {
      id: '/repos/new'
      path: '/repos/new'
      fullPath: '/repos/new'
      preLoaderRoute: typeof ReposNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/push': {
      id: '/api/dev/push'
      path: '/api/dev/push'
      fullPath: '/api/dev/push'
      preLoaderRoute: typeof ApiDevPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/git/credentials': {
      id: '/api/git/credentials'
      path: '/api/git/credentials'
      fullPath: '/api/git/credentials'
      preLoaderRoute: typeof ApiGitCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$repoSlug/': {
      id: '/repos/$repoSlug/'
      path: '/repos/$repoSlug'
      fullPath: '/repos/$repoSlug/'
      preLoaderRoute: typeof ReposRepoSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$repoSlug/decisions': {
      id: '/repos/$repoSlug/decisions'
      path: '/repos/$repoSlug/decisions'
      fullPath: '/repos/$repoSlug/decisions'
      preLoaderRoute: typeof ReposRepoSlugDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changes/$changeId/live': {
      id: '/api/changes/$changeId/live'
      path: '/api/changes/$changeId/live'
      fullPath: '/api/changes/$changeId/live'
      preLoaderRoute: typeof ApiChangesChangeIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repos/$repoSlug/': {
      id: '/api/repos/$repoSlug/'
      path: '/api/repos/$repoSlug'
      fullPath: '/api/repos/$repoSlug/'
      preLoaderRoute: typeof ApiReposRepoSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repos/$repoSlug/sessions': {
      id: '/api/repos/$repoSlug/sessions'
      path: '/api/repos/$repoSlug/sessions'
      fullPath: '/api/repos/$repoSlug/sessions'
      preLoaderRoute: typeof ApiReposRepoSlugSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMeRoute: ApiMeRoute,
  ChangesChangeIdRoute: ChangesChangeIdRoute,
  DecisionsDecisionIdRoute: DecisionsDecisionIdRoute,
  ReposNewRoute: ReposNewRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  ReposIndexRoute: ReposIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiDevPushRoute: ApiDevPushRoute,
  ApiGitCredentialsRoute: ApiGitCredentialsRoute,
  ReposRepoSlugDecisionsRoute: ReposRepoSlugDecisionsRoute,
  ReposRepoSlugIndexRoute: ReposRepoSlugIndexRoute,
  ApiChangesChangeIdLiveRoute: ApiChangesChangeIdLiveRoute,
  ApiReposRepoSlugSessionsRoute: ApiReposRepoSlugSessionsRoute,
  ApiReposRepoSlugIndexRoute: ApiReposRepoSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
